; PlatformIO project configuration
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.filesystem = littlefs

lib_deps =
    fastled/FastLED @ ^3.7.0
    mathieucarbou/ESPAsyncWebServer @ ^3.3.0
    bblanchon/ArduinoJson @ ^7.2.0

build_flags =
    -DFASTLED_ESP32_I2S=0
